projects:
  awsamplifyhooks:
    schemaPath: amplify/backend/api/awsamplifyhooks/build/schema.graphql
    includes:
      - packages/test/src/common/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ""
        docsFilePath: packages/test/src/common
        region: ap-southeast-2
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
