name: Create Pull Request

on:
  pull_request:
    pull_request:
      types: [opened, reopened]

jobs:
  Build_Distribution_Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Packages
        run: yarn install --pure-lockfile && yarn build
