name: Create Pull Request

on:
  pull_request:
    pull_request:
      types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # # extract branch name on pull request
      # - name: Print branch name
      #   if: github.event_name == 'pull_request'
      #   run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      # - run: echo "Creating Release for $BRANCH_NAME event."
      - name: Checkout repo
        uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Build Typescript
        run: yarn install --pure-lockfile && yarn build

      # - name: Push Build Files
      #   run: |
      #     echo "Test push commit to the remote in the workflow" >> test.txt

      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "actions@github.com"

      #     git add -A
      #     git pull origin HEAD:${{ github.event.pull_request.head.ref }}
      #     git commit -m "Update test.txt"
      #     git push origin HEAD:${{ github.event.pull_request.head.ref }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions[bot]
          author_email: actions@github.com
          message: "pushing dist"
          add: "."
