name: Create Pull Request

on:
  pull_request:
    pull_request:
      types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.event.pull_request.head.ref }}
      # - name: Build Typescript
      #   run: yarn install --pure-lockfile && yarn build
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v8
      #   with:
      #     author_name: github-actions[bot]
      #     author_email: actions@github.com
      #     message: "pushing dist"
      #     add: "**/dist/*"

      - name: Get Release Name
        uses: actions-ecosystem/action-regex-match@v2
        id: get_release_name
        with:
          text: "${{ github.event.pull_request.title }}"
          regex: '[v]([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?'
      - name: Check Test
        if: ${{ steps.get_release_name.outputs.match != '' }}
        run: echo "THIS IS RUNNING  ${{ steps.get_release_name.outputs.match }}"
