name: Build Typescript

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build Typescript
        run: yarn install --pure-lockfile && yarn build

      - name: Get Release Name
        uses: actions-ecosystem/action-regex-match@v2
        id: get_release_name
        with:
          text: "${{ github.event.pull_request.title }}"
          regex: '[v]([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?'

      - name: Get Tag Name
        uses: frabert/replace-string-action@v2.0
        id: get_tag_name
        with:
          pattern: "v"
          string: "${{ steps.get_release_name.outputs.match }}"
          replace-with: ""

      - name: Update version in package.json
        if: ${{ steps.get_tag_name.outputs.replaced }}
        uses: technote-space/package-version-check-action@v1
        with:
          NEXT_VERSION: "${{ steps.get_tag_name.outputs.replaced }}"
          COMMIT_MESSAGE: "updating package.json version"

      - name: Commit changes for the generated build
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions[bot]
          author_email: actions@github.com
          message: "[**/dist/**] generated build files"
          add: "**/dist/**"
