name: Build Typescript

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build Typescript
        run: yarn install --pure-lockfile && yarn build

      - name: Get Release Name
        uses: actions-ecosystem/action-regex-match@v2
        id: get_release_name
        with:
          text: '${{ github.event.pull_request.title }}'
          regex: '[v]([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?'

      - name: Update version in package.json
        if: ${{ steps.get_release_name.outputs.match }}
        uses: technote-space/package-version-check-action@v1
        with:
          NEXT_VERSION: '${{ steps.get_release_name.outputs.match }}'
          COMMIT_MESSAGE: '[package.json] updated package.json to ${{ steps.get_release_name.outputs.match }}'

      - name: Commit changes for the generated build
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions[bot]
          author_email: actions@github.com
          message: '[**/dist/**] generated build files'
          add: '**/dist/**'
