name: Create Pull Request

on:
  pull_request:
    pull_request:
    types: [opened, reopened]

jobs:
  Build_Distribution_Files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
