name: Create Release

on:
  push:
    branches:
      - release

env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Name
        uses: actions-ecosystem/action-regex-match@v2
        id: get_release_name
        with:
          text: "${{ github.event.head_commit.message }}"
          regex: '[v]([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?'

      # - name: Get Tag Name
      #   uses: bhowell2/github-substring-action
      #   id: get_tag_name
      #   with:
      #     value: "${{ steps.get_release_name.outputs.match }}"
      #     index_of_str: "v"

      - name: Create Tag
        id: tag_and_prepare_release
        uses: negz/create-tag@v1
        with:
          version: "${{ steps.get_release_name.outputs.match }}"
          message: "Creating Tag for ${{ steps.get_release_name.outputs.match }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload release notes
      #   if: steps.tag_and_prepare_release.outputs.tag
      #   uses: Roang-zero1/github-create-release-action@master
      #   with:
      #     release_title: ${{ steps.version_tag_from_commit_message.outputs.match }}
      #     created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
