name: Create Release

on:
  push:
    branches:
      - release

env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Find for semver in commit message
        uses: actions-ecosystem/action-regex-match@v2
        id: version_tag_from_commit_message
        with:
          text: "$COMMIT_MESSAGE"
          regex: '[v]([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?'
      - run: echo "TAG VERSION FOUND  ${{ steps.version_tag_from_commit_message.outputs.match }}"
      - name: Create Tag
        if: contains(${{ github.event.head_commit.message }}, 'Tag Version')
        id: tag_and_prepare_release
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.version_tag_from_commit_message.outputs.match }}.replace('v', '')
          message: Creating Tag for $TAG_VERSION
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload release notes
      #   if: steps.tag_and_prepare_release.outputs.tag
      #   uses: Roang-zero1/github-create-release-action@master
      #   with:
      #     release_title: ${{ steps.version_tag_from_commit_message.outputs.match }}
      #     created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
