name: Create Release

on:
  push:
    branches:
      - release

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Creating Release for ${{ github.event_name }} event."
