name: Create Release

on:
  push:
    branches:
      - release

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event.head_commit.message }} event."
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ github.event.head_commit.message }}
          message: Creating Tag for ${{ github.event.head_commit.message }
          token: ${{ secrets.GITHUB_TOKEN }}
