name: Create Tags and Release

on:
  pull_request:
    types: closed

jobs:
  create-tags-and-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'release'
    steps:
      - name: Get Release Name
        uses: actions-ecosystem/action-regex-match@v2
        id: get_release_name
        with:
          text: "${{ github.event.pull_request.title }}"
          regex: '[v]([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?'

      - name: Get Tag Name
        uses: frabert/replace-string-action@v2.0
        id: get_tag_name
        with:
          pattern: "v"
          string: "${{ steps.get_release_name.outputs.match }}"
          replace-with: ""

      - uses: actions/checkout@v2
      - name: Create Tags
        if: ${{ steps.get_release_name.outputs.match != '' }}
        id: tag_and_prepare_release
        uses: mathieudutour/github-tag-action@v6.0
        with:
          tag_prefix: ""
          custom_tag: "${{ steps.get_tag_name.outputs.replaced }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release notes
        uses: ncipollo/release-action@v1
        if: ${{ steps.get_release_name.outputs.match != '' }}
        with:
          name: ${{ steps.get_release_name.outputs.match }}
          tag: ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
