name: Create Release

on:
  push:
    branches:
      - release

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event.head_commit.message }} event."
